In [ ]:
from pathlib import Path
import pandas as pd

# Project root = folder where this notebook lives (graph-music-recs)
project_root = Path("./..").resolve()

# Path to the Kaggle dataset inside data_raw
data_dir = project_root / "data_raw" / "Million Song Dataset + Spotify + Last"

print("Project root:", project_root)
print("Data directory:", data_dir)

# List all files in the dataset folder
print("\nFiles in data_dir:")
for p in sorted(data_dir.iterdir()):
    print(" -", p.name)

Project root: /Users/shritej/graph-music-recs
Data directory: /Users/shritej/graph-music-recs/data_raw/Million Song Dataset + Spotify + Last

Files in data_dir:
 - .DS_Store
 - MP3-Example
 - Music Info.csv
 - User Listening History.csv

In [10]:
# Cell 2 – Inspect Music Info.csv

music_path = data_dir / "Music Info.csv"
print("Music Info path:", music_path)

# Load a sample (or full if it's not too large)
music_df = pd.read_csv(music_path)

print("\n=== Music Info: shape ===")
print(music_df.shape)

print("\n=== Music Info: columns ===")
print(music_df.columns.tolist())

print("\n=== Music Info: first 5 rows ===")
display(music_df.head())

Music Info path: /Users/shritej/graph-music-recs/data_raw/Million Song Dataset + Spotify + Last/Music Info.csv

=== Music Info: shape ===
(50683, 21)

=== Music Info: columns ===
['track_id', 'name', 'artist', 'spotify_preview_url', 'spotify_id', 'tags', 'genre', 'year', 'duration_ms', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature']

=== Music Info: first 5 rows ===

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,...,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj,"rock, alternative, indie, pop, alternative_roc...",NaN,2006,258613,0.409,...,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D,"rock, alternative, alternative_rock, 90s, grunge",RnB,1991,218920,0.508,...,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,https://p.scdn.co/mp3-preview/399c401370438be4...,0ancVQ9wEcHVd0RrGICTE4,"rock, alternative, indie, alternative_rock, in...",NaN,2004,237026,0.279,...,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I,"rock, alternative, indie, alternative_rock, in...",RnB,2008,238640,0.515,...,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

In [11]:
# Cell 3 – Inspect User Listening History.csv

history_path = data_dir / "User Listening History.csv"
print("User Listening History path:", history_path)

# Load the full file (if it's too big, we can switch to nrows=100000)
history_df = pd.read_csv(history_path)

print("\n=== User Listening History: shape ===")
print(history_df.shape)

print("\n=== User Listening History: columns ===")
print(history_df.columns.tolist())

print("\n=== User Listening History: first 5 rows ===")
display(history_df.head())

# Optional: peek at a few basic stats
print("\n=== Basic value counts (first 5 users & tracks) ===")
if "user_id" in history_df.columns:
    print("Distinct users:", history_df["user_id"].nunique())
    print(history_df["user_id"].value_counts().head())
if "track_id" in history_df.columns:
    print("\nDistinct tracks:", history_df["track_id"].nunique())
    print(history_df["track_id"].value_counts().head())

User Listening History path: /Users/shritej/graph-music-recs/data_raw/Million Song Dataset + Spotify + Last/User Listening History.csv

=== User Listening History: shape ===
(9711301, 3)

=== User Listening History: columns ===
['track_id', 'user_id', 'playcount']

=== User Listening History: first 5 rows ===

             track_id                                   user_id  playcount
0  TRIRLYL128F42539D1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
1  TRFUPBA128F934F7E1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
2  TRLQPQJ128F42AA94F  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
3  TRTUCUY128F92E1D24  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
4  TRHDDQG12903CB53EE  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1

=== Basic value counts (first 5 users & tracks) ===
Distinct users: 962037
user_id
ec6dfcf19485cb011e0b22637075037aae34cf26    784
4e11f45d732f4861772b2906f81a7d384552ad12    384
726da71c2c2ea119119a7957517fccd028d1be76    376
113255a012b2affeab62607563d03fbdf31b08e7    367
7adec7f006cb09482d36609d205293d8b61f030e    366
Name: count, dtype: int64

Distinct tracks: 30459
track_id
TRONYHY128F92C9D11    80656
TRUFTBY128F93450B8    39529
TRXWAZC128F9314B3E    30873
TRCPXID128F92D5D3C    30057
TRGCHLH12903CB7352    29708
Name: count, dtype: int64

In [12]:
# Cell 4 – Dataset profiling + graph schema planning

# --- Basic stats from both tables ---
total_history_rows = len(history_df)
n_users           = history_df["user_id"].nunique()
n_tracks_history  = history_df["track_id"].nunique()

n_tracks_music    = music_df["track_id"].nunique()
n_artists         = music_df["artist"].nunique()
n_genres_nonnull  = music_df["genre"].notna().sum()

print("=== Summary statistics ===")
print(f"User Listening History rows: {total_history_rows:,}")
print(f"Distinct users:             {n_users:,}")
print(f"Distinct tracks (history):  {n_tracks_history:,}")
print(f"Distinct tracks (music):    {n_tracks_music:,}")
print(f"Distinct artists:           {n_artists:,}")
print(f"Rows with non-null genre:   {n_genres_nonnull:,}")

# --- Track coverage: how many history tracks exist in music info? ---
tracks_history_set = set(history_df["track_id"].unique())
tracks_music_set   = set(music_df["track_id"].unique())

intersection_tracks = len(tracks_history_set & tracks_music_set)
coverage = intersection_tracks / n_tracks_history if n_tracks_history > 0 else 0.0

print("\n=== Track ID coverage ===")
print(f"Tracks in history only:      {n_tracks_history - intersection_tracks:,}")
print(f"Tracks in both tables:       {intersection_tracks:,}")
print(f"Coverage of history tracks by music info: {coverage:.2%}")

# --- Proposed graph schema (for your notes/report) ---
print("\n=== Proposed graph schema ===")
print("Nodes:")
print("  - User(user_id)")
print("  - Song(track_id, name, year, artist, genre, audio features like danceability, energy, etc.)")
print("  - Artist(artist)")
print("  - Genre(genre)  [optional]")
print("\nRelationships:")
print("  - (User)-[:LISTENED {playcount}]->(Song)")
print("  - (Song)-[:PERFORMED_BY]->(Artist)")
print("  - (Song)-[:IN_GENRE]->(Genre)  [optional]")

=== Summary statistics ===
User Listening History rows: 9,711,301
Distinct users:             962,037
Distinct tracks (history):  30,459
Distinct tracks (music):    50,683
Distinct artists:           8,317
Rows with non-null genre:   22,348

=== Track ID coverage ===
Tracks in history only:      0
Tracks in both tables:       30,459
Coverage of history tracks by music info: 100.00%

=== Proposed graph schema ===
Nodes:
  - User(user_id)
  - Song(track_id, name, year, artist, genre, audio features like danceability, energy, etc.)
  - Artist(artist)
  - Genre(genre)  [optional]

Relationships:
  - (User)-[:LISTENED {playcount}]->(Song)
  - (Song)-[:PERFORMED_BY]->(Artist)
  - (Song)-[:IN_GENRE]->(Genre)  [optional]

In [13]:
# Cell 5 – Deeper profiling: user activity, track popularity, genres

# --- User activity: how many tracks each user has listened to ---
user_activity = history_df.groupby("user_id")["track_id"].count()

print("=== User activity (tracks per user) ===")
print(user_activity.describe())   # count, mean, std, min, max, quartiles

print("\nTop 5 most active users (by number of tracks listened):")
display(user_activity.sort_values(ascending=False).head(5))

# --- Track popularity: how many users listened to each track ---
track_popularity = history_df.groupby("track_id")["user_id"].count()

print("\n=== Track popularity (users per track) ===")
print(track_popularity.describe())

print("\nTop 5 most popular tracks (by number of users):")
top_tracks = track_popularity.sort_values(ascending=False).head(5).reset_index()
top_tracks = top_tracks.merge(
    music_df[["track_id", "name", "artist"]],
    on="track_id",
    how="left"
)
display(top_tracks)

# --- Genre distribution (optional, for report text) ---
print("\n=== Top 10 genres (non-null) ===")
top_genres = (
    music_df[music_df["genre"].notna()]
    ["genre"].value_counts()
    .head(10)
)
display(top_genres)

=== User activity (tracks per user) ===
count    962037.000000
mean         10.094519
std          14.555314
min           1.000000
25%           3.000000
50%           5.000000
75%          11.000000
max         784.000000
Name: track_id, dtype: float64

Top 5 most active users (by number of tracks listened):

user_id
ec6dfcf19485cb011e0b22637075037aae34cf26    784
4e11f45d732f4861772b2906f81a7d384552ad12    384
726da71c2c2ea119119a7957517fccd028d1be76    376
113255a012b2affeab62607563d03fbdf31b08e7    367
7adec7f006cb09482d36609d205293d8b61f030e    366
Name: track_id, dtype: int64

=== Track popularity (users per track) ===
count    30459.000000
mean       318.831905
std       1105.034895
min          1.000000
25%         13.000000
50%         57.000000
75%        255.000000
max      80656.000000
Name: user_id, dtype: float64

Top 5 most popular tracks (by number of users):

             track_id  user_id                 name             artist
0  TRONYHY128F92C9D11    80656              Revelry      Kings of Leon
1  TRUFTBY128F93450B8    39529            Alejandro          Lady Gaga
2  TRXWAZC128F9314B3E    30873   Heartbreak Warfare         John Mayer
3  TRCPXID128F92D5D3C    30057                 Halo       Depeche Mode
4  TRGCHLH12903CB7352    29708  Party In The U.S.A.  The Barden Bellas

=== Top 10 genres (non-null) ===

genre
Rock          9965
Electronic    3710
Metal         2516
Pop           1145
Rap            821
Jazz           793
RnB            696
Reggae         691
Country        607
Punk           383
Name: count, dtype: int64

In [14]:
# Cell 6 – Create a sampled subset for quick experiments

from pathlib import Path

processed_dir = project_root / "data_processed"
sample_dir = processed_dir / "sample"
sample_dir.mkdir(parents=True, exist_ok=True)

print("Saving samples to:", sample_dir)

# 1) Sample a subset of users (e.g., 5,000 users)
n_sample_users = 5000

sample_user_ids = (
    history_df["user_id"]
    .drop_duplicates()
    .sample(n=n_sample_users, random_state=42)
)

history_sample = history_df[history_df["user_id"].isin(sample_user_ids)].copy()

print("Sample history shape:", history_sample.shape)

# 2) Get the tracks that appear in this subset
sample_track_ids = history_sample["track_id"].drop_duplicates()
music_sample = music_df[music_df["track_id"].isin(sample_track_ids)].copy()

print("Sample music info shape:", music_sample.shape)

# 3) Save to CSV for quick testing
history_sample_path = sample_dir / "user_listening_history_sample.csv"
music_sample_path   = sample_dir / "music_info_sample.csv"

history_sample.to_csv(history_sample_path, index=False)
music_sample.to_csv(music_sample_path, index=False)

print("\nSaved:")
print(" -", history_sample_path)
print(" -", music_sample_path)

Saving samples to: /Users/shritej/graph-music-recs/data_processed/sample
Sample history shape: (49172, 3)
Sample music info shape: (11736, 21)

Saved:
 - /Users/shritej/graph-music-recs/data_processed/sample/user_listening_history_sample.csv
 - /Users/shritej/graph-music-recs/data_processed/sample/music_info_sample.csv

In [15]:
# Cell 7 – Human-readable summary for your report

summary_lines = []

summary_lines.append("=== Dataset Summary (Million Song + Spotify + Last.fm) ===")
summary_lines.append(f"- Total user–track interactions: {total_history_rows:,}")
summary_lines.append(f"- Number of unique users: {n_users:,}")
summary_lines.append(f"- Number of unique tracks (history): {n_tracks_history:,}")
summary_lines.append(f"- Number of unique tracks (music metadata): {n_tracks_music:,}")
summary_lines.append(f"- Number of unique artists: {n_artists:,}")
summary_lines.append(f"- Rows with non-null genre values: {n_genres_nonnull:,}")
summary_lines.append(f"- Coverage of history tracks by music metadata: {coverage:.2%}")

summary_lines.append("")
summary_lines.append("=== Behavioral Patterns ===")
summary_lines.append(f"- Median tracks listened per user: {user_activity.median():.2f}")
summary_lines.append(f"- Mean tracks listened per user: {user_activity.mean():.2f}")
summary_lines.append(f"- Max tracks listened by a single user: {user_activity.max():.0f}")
summary_lines.append(f"- Median users per track: {track_popularity.median():.2f}")
summary_lines.append(f"- Mean users per track: {track_popularity.mean():.2f}")
summary_lines.append(f"- Max users listening to a single track: {track_popularity.max():.0f}")

summary_lines.append("")
summary_lines.append("=== Top Genres (non-null, by count) ===")
for genre, count in top_genres.items():
    summary_lines.append(f"- {genre}: {count}")

print("\n".join(summary_lines))

=== Dataset Summary (Million Song + Spotify + Last.fm) ===
- Total user–track interactions: 9,711,301
- Number of unique users: 962,037
- Number of unique tracks (history): 30,459
- Number of unique tracks (music metadata): 50,683
- Number of unique artists: 8,317
- Rows with non-null genre values: 22,348
- Coverage of history tracks by music metadata: 100.00%

=== Behavioral Patterns ===
- Median tracks listened per user: 5.00
- Mean tracks listened per user: 10.09
- Max tracks listened by a single user: 784
- Median users per track: 57.00
- Mean users per track: 318.83
- Max users listening to a single track: 80656

=== Top Genres (non-null, by count) ===
- Rock: 9965
- Electronic: 3710
- Metal: 2516
- Pop: 1145
- Rap: 821
- Jazz: 793
- RnB: 696
- Reggae: 691
- Country: 607
- Punk: 383